openapi: 3.0.0

info:
    title: Virus Total Reports
    description: Virus Total Reports
    version: "v2"

servers:
    - url: https://www.virustotal.com/

paths:
    
    /api/v3/ip_addresses/{ip}:
        get:
            operationId: VTIPReport
            summary: Lookup IP information
            parameters:
                - in: path
                  name: ip
                  schema:
                      type: string
                  required: true
                  description: The IP address to lookup
            responses:
                "200":
                    description: OK
    